### ISSUE TITLE
Cyprus belongs to the wrong continent

### ISSUE THREAD

**Issue by cosmindorobantu** [alexrabarts/iso_country_codes#19]
While Cyprus is closest to Asia Minor, it still belongs to Europe. Cyprus is also a member of the European union, so it's continent should be Europe.
https://github.com/alexrabarts/iso_country_codes/blob/master/lib/iso_country_codes/continent.rb#L162

**Comment by greysteil** [comment]
See https://github.com/alexrabarts/iso_country_codes/pull/22
