### ISSUE TITLE
Expanding to include per-country ISO 3166-2

### ISSUE THREAD

**Issue by donatoaz** [alexrabarts/iso_country_codes#24]
Hi,

I was interested in evolving this into containing the country state/provinces codes for ISO 3166-2. For example the ISO 3166-2:EC for Ecuador or ISO 3166-2:BR for Brazil.

Before I fork this, are there any comments or remarks or even guiding as to what pattern, format to follow?

Regards,

**Comment by alexrabarts** [comment]
Hi,

You should create a new file called `lib/iso_country_codes/iso_3166_2.rb` and populate it with the state/province codes in a similar way to the way the ISO 13616-1 IBAN codes have been implemented in `lib/iso_country_codes/iso_13616_1.rb`. e.g.

```
class BRA < Code #:nodoc:
  self.subdivision = 'BR'
end
```

You might also want to look at creating a rake task to scrape the data from a source such as Wikipedia to make future updates easier. You can see an example of this inside `rakelib`.

Finally, the terminology for ISO 3166-2 seems to vary (subdivision, state, province), so you might want to consider some method aliases.

Please also implement a `search_by_subdivision` method in `lib/iso_country_codes/iso_country_codes.rb`, tests and documentation in `README.md`.

Thanks!

Alex

**Comment by donatoaz** [comment]
Hi Alex,

Thank you for the feedback. Will get to it and report back.

Rgds,

Donato Azevedo
