### ISSUE TITLE
USA/US/United States

### ISSUE THREAD

**Issue by paulmars** [alexrabarts/iso_country_codes#28]
IsoCountryCodes.search_by_name("USA") -> nothing
IsoCountryCodes.search_by_name("US") -> bunch of things, not US

IsoCountryCodes.search_by_name("United states") -> works! :)

Maybe exactly as designed. Would you like a PR?

**Comment by greysteil** [comment]
Thanks for flagging this @paulmars. I'm agnostic on this one - on the one hand I like the simplicity of the current approach, on the other I can see it falls down for countries with alias names. Happy to accept a PR if it keeps things relatively simple, but I wouldn't consider this a bug.

**Comment by paulmars** [comment]
Thanks I agree.




Too many alias names might be annoying as well.
