### ISSUE TITLE
Country names, commands, and parenthesis

### ISSUE THREAD

**Issue by bettse** [alexrabarts/iso_country_codes#35]
I have a tool that returning country names to me, which I think pass to iso_country_codes.  In one case, it returned "Republic of Korea", and iso_country_codes couldn't find it and returned an error.  This got me digging, and I found this is because the "Republic of" part of the name is parenthetical in https://github.com/alexrabarts/iso_country_codes/blob/master/lib/iso_country_codes/iso_3166_1.rb

I'm not claiming this is an error or bug, because when it comes to naming things, its never easy.  It did lead me look at other records in the file, and I noticed that sometimes parenthesis are used for parts of the country name, other times its a comma that separates the parts.  I'm wondering if there is a reason for the difference, or if its an inconsistency?  If its an inconsistency, I wouldn't mind opening a PR for it.  

Also, for these cases, would it be feasible for iso_country_codes to do a comparison between the input, and a version of the country name where the parenthesis were removed and order flipped?  Again, I wouldn't be opposed to doing the leg work on the PR, but since I don't know the library very well, I wanted to find out if there may be other technical or non-technical reasons that this would be a bad idea before I started trying to code it up.

**Comment by greysteil** [comment]
Tricky one. The philosophy of this gem is to take official data wherever possible, in this case using https://github.com/alexrabarts/iso_country_codes/blob/master/rakelib/iso_3166_1.rb. I don't think we should be messing with that source data, but there's no reason we can't improve our `search_by_name` functionality, if that's what you're referring to?

**Comment by bettse** [comment]
Ah, it looks like the comma vs parenthesis goes all the way to https://www.iso.org/obp/ui/#search  In that case, I see the argument for maintaining consistency with the official data using Wikipedia.

My second idea was to improve the `search_by_name`.  For example, if the name contains a comma, the split on it, reverse the array, and join again ("Palestine, State of" => "State of Palestine") and check that against the input (along with all the other existing ways of checking).  Similarly for parenthesis, but something like stripping the `)`, and doing the split/reverse/join on the `(`.

Sound like something worth doing?

**Comment by greysteil** [comment]
I'd definitely be up for some improvements to `search_by_name`, and the split you've suggested sounds sensible. Even better might be to strip commas, brackets and common words (`the`, `of`) from both search string and country name string and arrange alphabetically before comparing? Will leave it to you to think through and put in a PR if you think useful.
